backend:
  name: github
  repo: trantrungtien-git/Sadaka
  branch: master
  # BỎ HẾT base_url và auth_endpoint

media_folder: "public/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "posts"
    label: "Bài viết"
    folder: "content/posts"
    create: true
    slug: "{{slug}}"
    format: frontmatter
    extension: md
    fields:
      - { label: "Tiêu đề", name: "title", widget: "string" }
      - {
          label: "Ngày đăng",
          name: "date",
          widget: "datetime",
          required: false,
        }
      - { label: "Nội dung", name: "body", widget: "markdown" }
